Spin the wheel
ssitvit/Games-and-Go pull request #298
Opened 2023-05-31 05:32 UTC by ePSA-eJya

2023-06-01 16:18 UTC, admindebu commented
Please resolve merge conflict

2023-06-01 16:31 UTC, ePSA-eJya commented
> Please resolve merge conflict

i have resolved merge conflict.

2023-06-03 06:50 UTC, ePSA-eJya commented
please help resolve this
![image](https://github.com/ssitvit/Games-and-Go/assets/120899038/f12d2c3a-595e-4361-b375-30fb903ab232)

2023-06-05 07:05 UTC, raj03kumar requested changes
The checks didn't pass. Kindly resolve it.

2023-06-05 07:05 UTC, closed without merging